export const FirebaseConstants = Object.freeze({
	API_KEY: process.env.VUE_APP_FIREBASE_API_KEY,
	AUTH_DOMAIN: process.env.VUE_APP_FIREBASE_AUTH_DOMAIN,
	DATABASE_URL: process.env.VUE_APP_DATABASE_URL,
	PROJECT_ID: process.env.VUE_APP_FIREBASE_PROJECT_ID,
	STORAGE_BUCKET: process.env.VUE_APP_FIREBASE_STORAGE_BUCKET,
	MESSAGING_SENDER_ID: process.env.VUE_APP_FIREBASE_MESSAGING_SENDER_ID,
	APP_ID: process.env.VUE_APP_FIREBASE_APP_ID,
})
